# Generated by Django 3.2.6 on 2021-08-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_datastructure_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastructure',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
