# Generated by Django 3.2.6 on 2021-09-17 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0007_auto_20210917_1247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
