# Generated by Django 3.2.6 on 2021-08-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firstApp', '0002_delete_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('videos', models.CharField(max_length=50)),
                ('theory', models.CharField(max_length=50)),
            ],
        ),
    ]
