# Generated by Django 3.2.6 on 2021-09-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0006_subjects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datastructure',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='image',
        ),
    ]
